# Generated by Django 5.1.6 on 2025-02-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_hq_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hq_user_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
