version: "3.9"

services:
  web:
    build: .
    name: chat-messaging-web
    command: sh /app/includes/scripts/${RUN_SCRIPT}
    volumes:
      - .:/app
    ports:
      - "${EXT_BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      chat-messaging-db:
        condition: service_healthy
      chat-messaging-redis:
        condition: service_started
    networks:
      - chat_network

  db:
    name: chat-messaging-db
    restart: unless-stopped
    image: postgres:14
    env_file:
      - .env
    ports:
      - "${EXT_DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    name: chat-messaging-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "${EXT_REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:

networks:
  chat_network:
    external: true
