# Generated by Django 5.1.6 on 2025-02-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
