# Generated by Django 5.1.6 on 2025-02-25 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatroommessage_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroommessage',
            name='read',
        ),
        migrations.CreateModel(
            name='ChatRoomMessageReadReciepts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chatroommember')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chatroommessage')),
            ],
            options={
                'unique_together': {('message', 'member')},
            },
        ),
    ]
