# Generated by Django 5.1.6 on 2025-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_chatroommessage_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
